# Generated by Django 3.2.13 on 2022-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tables',
                'ordering': ('table_no',),
            },
        ),
    ]
