# Generated by Django 3.1.4 on 2022-03-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0009_auto_20220318_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdelivery',
            name='speed',
        ),
    ]
