# Generated by Django 3.2.13 on 2022-04-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0010_remove_tempdelivery_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skyvy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_no', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
