# Generated by Django 3.1.4 on 2022-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')])),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
